<a href="https://colab.research.google.com/github/SarthakBMSCE/BIS_Lab_1BM22CS352/blob/main/BIS_LAB_Parallel_Cellular_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from multiprocessing import Pool

# Define the grid size and number of iterations
N = 100 # Grid size
iterations = 10

# Initialize the grid with random states (0 or 1)
grid = np.random.randint(2, size=(N, N))

# Function to compute the next state of a cell
def compute_next_state(args):
    grid, x, y = args
    neighbors = [
        (x-1, y-1), (x-1, y), (x-1, y+1),
        (x, y-1), (x, y+1),
        (x+1, y-1), (x+1, y), (x+1, y+1),
    ]
    live_neighbors = sum(grid[i % N, j % N] for i, j in neighbors)
    if grid[x, y] == 1:
        return 1 if live_neighbors in (2, 3) else 0
    else:
        return 1 if live_neighbors == 3 else 0

# Parallel update function
def update_grid(grid):
    args = [(grid, x, y) for x in range(N) for y in range(N)]
    with Pool() as pool:
        new_states = pool.map(compute_next_state, args)
    return np.array(new_states).reshape((N, N))

# Run the simulation
for _ in range(iterations):
    grid = update_grid(grid)
    print(grid)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [1 1 1 ... 0 1 1]
 [1 1 0 ... 0 0 0]]
[[1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 1 1]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [

In [ ]:
import numpy as np
from multiprocessing import Pool

def update_cell(cell_index, grid, size):
    # Unpack the cell index (cell_index should be a tuple (x, y))
    x, y = cell_index

    # Define neighbors' indices (using a 2D Moore neighborhood)
    neighbors = [
        ((x-1) % size, y), ((x+1) % size, y),
        (x, (y-1) % size), (x, (y+1) % size)
    ]

    # Compute new state (this could be any rule like majority, XOR, etc.)
    new_state = sum(grid[n[0], n[1]] for n in neighbors) % 2  # example: majority rule
    return (x, y, new_state)

def parallel_update(grid, size, num_iterations):
    pool = Pool(processes=4)  # Use 4 processes for parallel execution

    for iteration in range(num_iterations):
        print(f"Iteration {iteration + 1}:")

        indices = [(x, y) for x in range(size) for y in range(size)]
        result = pool.starmap(update_cell, [(i, grid, size) for i in indices])

        # Update the grid with the new states
        for x, y, new_state in result:
            grid[x, y] = new_state

        # Print the updated grid for this iteration
        print(grid)

    return grid

# Initialize grid with random states (0 or 1)
grid_size = 4
grid = np.random.randint(2, size=(grid_size, grid_size))

# Number of iterations to run
num_iterations = 2


# Parallel update and print iterations
updated_grid = parallel_update(grid, grid_size, num_iterations)


Iteration 1:
[[1 0 0 1]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 0 1]]
Iteration 2:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
import numpy as np
from multiprocessing import Pool

def update_cell(cell_index, grid, size):
    # Unpack the cell index (cell_index should be a tuple (x, y))
    x, y = cell_index

    # Define neighbors' indices (using a 2D Moore neighborhood)
    neighbors = [
        ((x-1) % size, y), ((x+1) % size, y),
        (x, (y-1) % size), (x, (y+1) % size)
    ]

    # Compute new state (this could be any rule like majority, XOR, etc.)
    new_state = sum(grid[n[0], n[1]] for n in neighbors) % 2  # example: majority rule
    return (x, y, new_state)

def parallel_update(grid, size, num_iterations):
    pool = Pool(processes=4)  # Use 4 processes for parallel execution

    for iteration in range(num_iterations):
        print(f"Iteration {iteration + 1}:")

        indices = [(x, y) for x in range(size) for y in range(size)]
        result = pool.starmap(update_cell, [(i, grid, size) for i in indices])

        # Update the grid with the new states
        for x, y, new_state in result:
            grid[x, y] = new_state

        # Print the updated grid for this iteration
        print(grid)

    return grid

# Initialize grid with random states (0 or 1)
grid_size = 10
grid = np.random.randint(2, size=(grid_size, grid_size))

# Print the initial grid state
print("Initial state:")
print(grid)

# Number of iterations to run
num_iterations = 2

# Parallel update and print iterations
updated_grid = parallel_update(grid, grid_size, num_iterations)


Initial state:
[[0 0 1 0 0 0 0 1 0 1]
 [1 1 0 1 0 1 1 1 1 0]
 [1 1 1 0 1 0 1 1 1 1]
 [1 1 0 0 1 0 0 0 1 1]
 [1 0 1 0 0 0 0 0 0 0]
 [0 1 1 0 1 1 1 0 1 1]
 [0 1 1 0 1 0 0 1 0 0]
 [1 1 1 0 1 1 1 0 1 0]
 [0 0 0 0 1 1 0 0 0 1]
 [0 1 0 0 0 1 1 1 0 1]]
Iteration 1:
[[0 1 0 0 0 0 1 0 1 1]
 [0 0 0 0 1 1 1 0 0 0]
 [0 0 1 1 1 1 0 1 0 1]
 [0 0 1 1 1 1 1 0 0 1]
 [1 0 1 1 0 1 1 0 0 1]
 [1 0 1 0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1 0 1 1]
 [1 1 0 0 1 1 1 1 0 1]
 [0 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 0]]
Iteration 2:
[[0 0 1 0 1 0 1 0 1 1]
 [0 1 1 0 0 1 0 0 1 0]
 [1 1 0 1 0 1 0 0 0 1]
 [0 1 1 0 1 0 0 0 1 0]
 [0 0 1 0 1 0 1 0 0 1]
 [0 1 0 0 0 1 1 0 1 0]
 [0 0 0 1 0 0 1 0 0 1]
 [0 0 1 0 1 0 0 0 1 1]
 [0 0 1 1 1 0 1 0 0 1]
 [0 1 1 1 0 1 0 1 1 0]]
